//
// THIS FILE HAS BEEN AUTOGENERATED. DO NOT MODIFY.
//

import * as t from 'io-ts'
import { state } from './state'

export const certifactionSchema = JSON.parse(`{
  "type": "object",
  "properties": {
    "currentState": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string",
          "format": "time",
          "default": "Date.now"
        },
        "code": {
          "type": "string",
          "default": "STAGING"
        }
      }
    },
    "states": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "time",
            "default": "Date.now"
          },
          "code": {
            "type": "string",
            "default": "STAGING"
          }
        }
      }
    },
    "transaction": {
      "type": "string"
    }
  }
}`)

export const certifaction = t.partial({
  currentState: state,
  states: t.array(state),
  transaction: t.string,
})

export type certifaction = t.TypeOf<typeof certifaction>
