//
// THIS FILE HAS BEEN AUTOGENERATED. DO NOT MODIFY.
//

import * as t from 'io-ts'

export const clientSchema = JSON.parse(`{
  "type": "object",
  "properties": {
    "clientId": {
      "type": "string"
    },
    "clientMail": {
      "type": "string"
    },
    "clientPhone": {
      "type": "string"
    },
    "clientFid": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "fidShop": {
            "type": "string"
          },
          "fidId": {
            "type": "string"
          }
        }
      }
    }
  }
}`)

export const client = t.partial({
  clientId: t.string,
  clientMail: t.string,
  clientPhone: t.string,
  clientFid: t.array(
    t.partial({
      fidShop: t.string,
      fidId: t.string,
    })
  ),
})

export type client = t.TypeOf<typeof client>
