//
// THIS FILE HAS BEEN AUTOGENERATED. DO NOT MODIFY.
//

import * as t from 'io-ts'

export const priceSchema = JSON.parse(`{
  "type": "object",
  "properties": {
    "amount": {
      "type": "number"
    },
    "scale": {
      "type": "number"
    },
    "currency": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string",
          "default": "EUR"
        },
        "symbol": {
          "type": "string",
          "default": "€"
        }
      },
      "required": [
        "code",
        "symbol"
      ]
    }
  },
  "required": [
    "amount",
    "scale",
    "currency"
  ]
}`)

export const price = t.type({
  amount: t.number,
  scale: t.number,
  currency: t.type({
    code: t.string,
    symbol: t.string,
  }),
})

export type price = t.TypeOf<typeof price>
