//
// THIS FILE HAS BEEN AUTOGENERATED. DO NOT MODIFY.
//

import * as t from 'io-ts'

export const stateSchema = JSON.parse(`{
  "type": "object",
  "properties": {
    "date": {
      "type": "string",
      "format": "time",
      "default": "Date.now"
    },
    "code": {
      "type": "string",
      "default": "STAGING"
    }
  }
}`)

export const state = t.partial({
  date: t.string,
  code: t.string,
})

export type state = t.TypeOf<typeof state>
